config/routes.rb
Rails.application.routes.draw do
  root 'urls#index'

  resources :urls

  get '/urls/:id/short' => 'urls#short'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  validates :long_url, uniqueness: true
  validates :long_url, format: {with: (URI::regexp(['http','https'])),
  message: "url entered is invalid, please enter a url with 'https://'"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def index
    @url = Url.all
  end

  def show
    @url = Url.find(params[:id])
  end

  def new
    @url = Url.new
  end

  def edit
    @url = Url.find(params[:id])
  end

  def create
    @url = Url.new(long_url: url_params[:long_url], short_url: rand(36**4).to_s(36))
    if @url.save
      redirect_to @url
    else
      render 'new'
    end
  end

  def update
    @url = Url.find(params[:id])

    if @url.update(url_params)
      redirect_to url_path
    else
      render 'edit'
    end
  end

  def destroy
    @url = Url.find(params[:id])
    @url.destroy
    redirect_to urls_path
  end

  def short
    @url = Url.find(params[:id])
    redirect_to @url.long_url
  end

  private
  def url_params
    params.require(:url).permit(:long_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bitly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/_form.html.erb
<%= form_for @url do |f|%>
<p>
  <%=f.label "Type your URL here : "%>
  <%=f.text_field :long_url%>
</p>

<p>
  <%=f.submit%>
</p>

<%end%>

app/views/urls/edit.html.erb
<h2>Edit Article</h2>
<%=render 'form'%>
<%=link_to 'Back', url_path%>

app/views/urls/index.html.erb
<h1>Apparently Bitly</h1>
<p><%=link_to 'New', new_url_path%></p>
<table>
    <tr>
      <th>Original URL : </th>
      <th>Shortened URL :</th>
    </tr>

    <% @url.each do |url|%>
    <tr>
      <td><a href= <%=url.long_url%>><%=url.long_url%></a></td>
      <td>bitly.com/<%=link_to url.short_url, controller: :urls, action: :short, id: url%></td>
      <td><%=link_to 'Show', url_path(url)%></td>
      <td><%=link_to 'Delete', url_path(url), method: :delete, data: { confirm: "Are you sure?"}%></td>
      <td><%= link_to 'Edit', edit_url_path(url)%></td>
    </tr>
    <%end%>
</table>

app/views/urls/new.html.erb
<h1>New URL</h1>
<%= render 'form' %>
<%= link_to 'Back', urls_path%>

app/views/urls/show.html.erb
<h2>This is me, showing you a URL</h2>
<p><%=@url.long_url%></p>
<p><%=@url.short_url%></p>
<%=link_to 'Back', urls_path%>